// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplyChain.DatabaseContext;

#nullable disable

namespace SupplyChain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250725063512_AddProductPhotos1")]
    partial class AddProductPhotos1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SupplyChain.DatabaseContext.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SupplyChain.DatabaseContext.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SupplyChain.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("SupplyChain.Models.ApprovalComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("ApprovalComments");
                });

            modelBuilder.Entity("SupplyChain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("SupplyChain.Models.CategoryApprovalStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryApprovalStages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Role = 2,
                            StageOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Role = 3,
                            StageOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Role = 1,
                            StageOrder = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Role = 3,
                            StageOrder = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Role = 2,
                            StageOrder = 1
                        });
                });

            modelBuilder.Entity("SupplyChain.Models.CreateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("SupplyChain.Models.InventoryLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryLogs");
                });

            modelBuilder.Entity("SupplyChain.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpayOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpayPaymentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpaySignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SupplyChain.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SupplyChain.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CurrentStock = 50,
                            Description = "Ergonomic Bluetooth wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 899m,
                            ProductBrandId = 1,
                            ProductTypeId = 1,
                            Threshold = 10
                        },
                        new
                        {
                            ProductId = 2,
                            CurrentStock = 30,
                            Description = "RGB mechanical keyboard with macro support",
                            Name = "Gaming Keyboard",
                            Price = 1899m,
                            ProductBrandId = 1,
                            ProductTypeId = 1,
                            Threshold = 5
                        },
                        new
                        {
                            ProductId = 3,
                            CurrentStock = 20,
                            Description = "Adjustable mesh back office chair",
                            Name = "Office Chair",
                            Price = 4999m,
                            ProductBrandId = 2,
                            ProductTypeId = 2,
                            Threshold = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CurrentStock = 25,
                            Description = "Minimalist study desk with drawers",
                            Name = "Study Table",
                            Price = 3599m,
                            ProductBrandId = 2,
                            ProductTypeId = 2,
                            Threshold = 5
                        },
                        new
                        {
                            ProductId = 5,
                            CurrentStock = 70,
                            Description = "CBSE Grade 10 Mathematics",
                            Name = "Mathematics Textbook",
                            Price = 399m,
                            ProductBrandId = 3,
                            ProductTypeId = 3,
                            Threshold = 15
                        },
                        new
                        {
                            ProductId = 6,
                            CurrentStock = 50,
                            Description = "Lab workbook with experiment logs",
                            Name = "Science Workbook",
                            Price = 299m,
                            ProductBrandId = 3,
                            ProductTypeId = 3,
                            Threshold = 10
                        },
                        new
                        {
                            ProductId = 7,
                            CurrentStock = 40,
                            Description = "1.5L electric kettle with auto shut-off",
                            Name = "Electric Kettle",
                            Price = 1499m,
                            ProductBrandId = 4,
                            ProductTypeId = 4,
                            Threshold = 8
                        },
                        new
                        {
                            ProductId = 8,
                            CurrentStock = 35,
                            Description = "24cm frying pan with glass lid",
                            Name = "Non-stick Frying Pan",
                            Price = 799m,
                            ProductBrandId = 4,
                            ProductTypeId = 4,
                            Threshold = 6
                        },
                        new
                        {
                            ProductId = 9,
                            CurrentStock = 10,
                            Description = "Wireless printer with duplex printing",
                            Name = "Inkjet Printer",
                            Price = 6599m,
                            ProductBrandId = 5,
                            ProductTypeId = 1,
                            Threshold = 2
                        },
                        new
                        {
                            ProductId = 10,
                            CurrentStock = 50,
                            Description = "Waterproof 15.6-inch laptop backpack",
                            Name = "Laptop Backpack",
                            Price = 999m,
                            ProductBrandId = 2,
                            ProductTypeId = 2,
                            Threshold = 7
                        },
                        new
                        {
                            ProductId = 11,
                            CurrentStock = 80,
                            Description = "200-page graph notebook for math",
                            Name = "Graph Notebook",
                            Price = 199m,
                            ProductBrandId = 3,
                            ProductTypeId = 3,
                            Threshold = 10
                        },
                        new
                        {
                            ProductId = 12,
                            CurrentStock = 30,
                            Description = "Compact 300W kitchen blender",
                            Name = "Hand Blender",
                            Price = 1199m,
                            ProductBrandId = 4,
                            ProductTypeId = 4,
                            Threshold = 5
                        },
                        new
                        {
                            ProductId = 13,
                            CurrentStock = 40,
                            Description = "Noise-cancelling TWS with mic",
                            Name = "Wireless Earbuds",
                            Price = 2499m,
                            ProductBrandId = 1,
                            ProductTypeId = 1,
                            Threshold = 8
                        },
                        new
                        {
                            ProductId = 14,
                            CurrentStock = 15,
                            Description = "5-layer wooden shelf for study room",
                            Name = "Book Shelf",
                            Price = 2499m,
                            ProductBrandId = 2,
                            ProductTypeId = 2,
                            Threshold = 3
                        },
                        new
                        {
                            ProductId = 15,
                            CurrentStock = 60,
                            Description = "Competitive exam prep book for Physics",
                            Name = "Physics Guide",
                            Price = 449m,
                            ProductBrandId = 3,
                            ProductTypeId = 3,
                            Threshold = 12
                        },
                        new
                        {
                            ProductId = 16,
                            CurrentStock = 25,
                            Description = "5L stainless steel cooker",
                            Name = "Steel Pressure Cooker",
                            Price = 2299m,
                            ProductBrandId = 4,
                            ProductTypeId = 4,
                            Threshold = 5
                        },
                        new
                        {
                            ProductId = 17,
                            CurrentStock = 35,
                            Description = "10W portable waterproof speaker",
                            Name = "Bluetooth Speaker",
                            Price = 1999m,
                            ProductBrandId = 1,
                            ProductTypeId = 1,
                            Threshold = 7
                        },
                        new
                        {
                            ProductId = 18,
                            CurrentStock = 8,
                            Description = "4-seater modern dining set",
                            Name = "Dining Table Set",
                            Price = 7999m,
                            ProductBrandId = 2,
                            ProductTypeId = 2,
                            Threshold = 2
                        },
                        new
                        {
                            ProductId = 19,
                            CurrentStock = 55,
                            Description = "Comprehensive English grammar reference",
                            Name = "English Grammar Book",
                            Price = 349m,
                            ProductBrandId = 3,
                            ProductTypeId = 3,
                            Threshold = 10
                        },
                        new
                        {
                            ProductId = 20,
                            CurrentStock = 22,
                            Description = "2-slice toaster with browning control",
                            Name = "Toaster",
                            Price = 999m,
                            ProductBrandId = 4,
                            ProductTypeId = 4,
                            Threshold = 5
                        });
                });

            modelBuilder.Entity("SupplyChain.Models.ProductBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IKEA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oxford"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Prestige"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HP"
                        });
                });

            modelBuilder.Entity("SupplyChain.Models.ProductPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPhotos");

                    b.HasData(
                        new
                        {
                            PhotoId = 1,
                            IsPrimary = true,
                            ProductId = 1,
                            PublicId = "wireless_mouse",
                            Url = "https://res.cloudinary.com/your-cloud/image/upload/v162876/wireless_mouse.jpg"
                        },
                        new
                        {
                            PhotoId = 2,
                            IsPrimary = true,
                            ProductId = 7,
                            PublicId = "bluetooth-speaker_egazpg",
                            Url = "https://res.cloudinary.com/dtryjgzaj/image/upload/v1753422073/SupplyChain/bluetooth-speaker_egazpg.webp"
                        },
                        new
                        {
                            PhotoId = 3,
                            IsPrimary = true,
                            ProductId = 2,
                            PublicId = "keyboard_qisjqv",
                            Url = "https://res.cloudinary.com/dtryjgzaj/image/upload/v1753422073/SupplyChain/keyboard_qisjqv.webp"
                        },
                        new
                        {
                            PhotoId = 4,
                            IsPrimary = true,
                            ProductId = 20,
                            PublicId = "toaster_ujtplk",
                            Url = "https://res.cloudinary.com/dtryjgzaj/image/upload/v1753422073/SupplyChain/toaster_ujtplk.webp"
                        },
                        new
                        {
                            PhotoId = 5,
                            IsPrimary = true,
                            ProductId = 19,
                            PublicId = "english_siabfk",
                            Url = "https://res.cloudinary.com/dtryjgzaj/image/upload/v1753422073/SupplyChain/english_siabfk.webp"
                        },
                        new
                        {
                            PhotoId = 6,
                            IsPrimary = true,
                            ProductId = 16,
                            PublicId = "kettle_bbamzn",
                            Url = "https://res.cloudinary.com/dtryjgzaj/image/upload/v1753422073/SupplyChain/kettle_bbamzn.webp"
                        },
                        new
                        {
                            PhotoId = 7,
                            IsPrimary = true,
                            ProductId = 19,
                            PublicId = "dinnig_dk4dxi",
                            Url = "https://res.cloudinary.com/dtryjgzaj/image/upload/v1753422072/SupplyChain/dinnig_dk4dxi.webp"
                        },
                        new
                        {
                            PhotoId = 8,
                            IsPrimary = true,
                            ProductId = 15,
                            PublicId = "cld-sample-3",
                            Url = "https://res.cloudinary.com/dtryjgzaj/image/upload/v1692335025/SupplyChain/cld-sample-5.jpg"
                        },
                        new
                        {
                            PhotoId = 9,
                            IsPrimary = true,
                            ProductId = 16,
                            PublicId = "cld-sample-4",
                            Url = "https://res.cloudinary.com/dtryjgzaj/image/upload/v1692335024/SupplyChain/cld-sample-4.jpg"
                        });
                });

            modelBuilder.Entity("SupplyChain.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Educational"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kitchen"
                        });
                });

            modelBuilder.Entity("SupplyChain.Models.RestockRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ShortageQty")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("AdminId");

                    b.HasIndex("ProductId");

                    b.ToTable("RestockRequests");
                });

            modelBuilder.Entity("SupplyChain.Models.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SupplyChain.DatabaseContext.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SupplyChain.DatabaseContext.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SupplyChain.DatabaseContext.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SupplyChain.DatabaseContext.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyChain.DatabaseContext.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SupplyChain.DatabaseContext.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupplyChain.Models.Approval", b =>
                {
                    b.HasOne("SupplyChain.Models.CreateRequest", "Request")
                        .WithMany("Approvals")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SupplyChain.Models.ApprovalComment", b =>
                {
                    b.HasOne("SupplyChain.Models.CreateRequest", null)
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupplyChain.Models.CategoryApprovalStage", b =>
                {
                    b.HasOne("SupplyChain.Models.Category", "Category")
                        .WithMany("Stages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SupplyChain.Models.CreateRequest", b =>
                {
                    b.HasOne("SupplyChain.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SupplyChain.Models.InventoryLog", b =>
                {
                    b.HasOne("SupplyChain.Models.Product", "Product")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyChain.DatabaseContext.ApplicationUser", "User")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupplyChain.Models.Order", b =>
                {
                    b.HasOne("SupplyChain.DatabaseContext.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupplyChain.Models.OrderItem", b =>
                {
                    b.HasOne("SupplyChain.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyChain.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupplyChain.Models.Product", b =>
                {
                    b.HasOne("SupplyChain.Models.ProductBrand", "ProductBrand")
                        .WithMany("Products")
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyChain.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("SupplyChain.Models.ProductPhoto", b =>
                {
                    b.HasOne("SupplyChain.Models.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupplyChain.Models.RestockRequest", b =>
                {
                    b.HasOne("SupplyChain.DatabaseContext.ApplicationUser", "Admin")
                        .WithMany("RestockRequests")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyChain.Models.Product", "Product")
                        .WithMany("RestockRequests")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupplyChain.DatabaseContext.ApplicationUser", b =>
                {
                    b.Navigation("InventoryLogs");

                    b.Navigation("Orders");

                    b.Navigation("RestockRequests");
                });

            modelBuilder.Entity("SupplyChain.Models.Category", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("SupplyChain.Models.CreateRequest", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SupplyChain.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SupplyChain.Models.Product", b =>
                {
                    b.Navigation("InventoryLogs");

                    b.Navigation("OrderItems");

                    b.Navigation("Photos");

                    b.Navigation("RestockRequests");
                });

            modelBuilder.Entity("SupplyChain.Models.ProductBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SupplyChain.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
